/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_danmaku_util_NativeUtil */

#ifndef _Included_com_danmaku_util_NativeUtil
#define _Included_com_danmaku_util_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_danmaku_util_NativeUtil
 * Method:    SetWindowBackgroundTransparent
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_danmaku_util_NativeUtil_SetWindowBackgroundTransparent
  (JNIEnv *, jclass, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
